(define square-model '(scale (0.5 0.5)
                       (polygon :2d-triangle-strip (-1 -1 1 -1 -1 1 1 1))))
(define start-time (foxgl:timestamp))
(define model '(scale (0.25 0.25 0.25)
       (let ((dt (* 0.000001 (- (foxgl:timestamp) start-time)))
             (sway (* 0.1 (sin dt))))
         (translate (0 0 0)
         (scale (8.0 8.0)
            (rgb (0.6 0.6 1.0)
           (bind square-model))
           (translate (0 -0.55)
            (rgb (0.6 1.0 0.6)
             (bind square-model)
              (translate (0.3)
               (rotate (0 0 0.1)
                (bind square-model)))
              )))
         
       (translate (-0.225 -0.225 0.0)
        (rotate (0 0 0)
        (rgb (0.7 0.4 0.4)
         (bind square-model)
         (for i (-0.5 0.5)
          (rotate (0 0 (bind (+ i sway)))
           (translate (0 0.9 0)
            (scale (0.7 1.0)
                   (bind square-model))
            
            (for i (-0.5 0.5)
             (scale (0.8 0.8)
              (rotate (0 0 (bind (+ i sway)))
               (translate (0 0.8 0.0)
                (scale (0.7 1.0)
                 (bind square-model))
                (for i (-0.5 0.5)
                 (scale (0.8 0.8)
                  (rotate (0 0 (bind (+ i sway)))
                   (translate (0 0.8 0)
                    (scale (0.7 1.0)
                     (bind square-model))
                    (for i (-0.5 0.5)
                     (scale (0.8 0.8)
                      (rotate (0 0 (bind i))
                       (translate (0 0.8 0)
                        (scale (0.7 1.0)
                         (bind square-model))
                        (for i (-0.5 0.5)
                         (scale (0.8 0.8)
                          (rotate (0 0 (bind (+ sway i)))
                                  (translate (0 0.8)
                                             (rgb (0.33 0.66 0.33)
                                             (scale (0.7 1.0)
                                                    (bind square-model))
                                             (for i (-0.5 0.5)
                                                  (scale (0.8 0.8)
                                                         (rotate (0 0 (bind (+ sway i)))
                                                                 (translate (0 0.8)
                                                                            (scale (0.7 1.0)
                                                                                   
                                                                                   (bind square-model))
                
                                                                            )))))
                                             ))))
                        ))))
                    ))))
                ))))
            )))
         
         )))))))
