(define test-other nil)
(let ((color2 '(1 2 3 4))
      (a1 0)
      (a2 0)
      (a3 0)
      (a4 0)
      (a5 0)
      (a6 0)
      (a7 0)
      (a8 0)
      (a9 0)
      (a10 10)
      (get-thing (lambda () (println 'a)))
      )
  (set! test-other
        (lambda ()
          (println (list a1 a2 a3 a4 a5 a6 a7 a8 a9 a10))
          (println color2)
          (get-thing)
          )))
