name: C

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install packages
      run: sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev libopenal-dev libglfw3-dev
    - name: make
      run: make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: |
          fox
          demos/*
          lisp/*
          Readme.md
          DejaVuSans.ttf


      
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        # Make sure to set a version number!
        version: 3.1.37
        # This is the name of the cache folder.
        # The cache folder will be placed in the build directory,
        #  so make sure it doesn't conflict with anything!
        actions-cache-folder: 'emsdk-cache'

    - name: Verify
      run: emcc -v
    - name: install packages
      run: sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev libopenal-dev libglfw3-dev
    - name: Make Iron
      run: make -C iron wasm
    - name: make
      run: make index.js
    - name: list files
      run: ls 
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasmbuild
        path: |
          index.js
          index.wasm
          index.html
   
